package com.bocoo.pay.enums;

public enum ReconciliationAnomalyType {
    CHANNEL_SUCCESS_LOCAL_PENDING,
    PAYMENT_SUCCESS_ORDER_UNPAID,
    PAYMENT_FACT_MISMATCH,
    PAYEE_MISMATCH,
    WEBHOOK_SIGNATURE_FAILED,
    WEBHOOK_PROCESS_FAILED,
    PAYMENT_LINK_MISSING,
    DUPLICATE_SUCCESS_ATTEMPT
}
