# MQTT鐩稿叧閰嶇疆
mqtt:
  device:
    load:
      # 鏄惁鍚敤璁惧鑷姩鍔犺浇鍔熻兘锛岄粯璁ゅ惎鐢? 寮€鍙戠幆澧?绂佺敤~ 涓嶇劧浼氬鑷村拰鏈嶅姟鍣ㄥ啿绐侊紱
      enabled: false
# websocket閰嶇疆
websocket:
  port: 2831
  sendUserid: 1966049982171709442
--- # 鏁版嵁婧愰厤缃?
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 鍔ㄦ€佹暟鎹簮鏂囨。 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 鎬ц兘鍒嗘瀽鎻掍欢(鏈夋€ц兘鎹熻€?涓嶅缓璁敓浜х幆澧冧娇鐢?
      p6spy: true
      # 璁剧疆榛樿鐨勬暟鎹簮鎴栬€呮暟鎹簮缁?榛樿鍊煎嵆涓?master
      primary: master
      # 涓ユ牸妯″紡 鍖归厤涓嶅埌鏁版嵁婧愬垯鎶ラ敊
      strict: true
      datasource:
        # 涓诲簱鏁版嵁婧?
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 鎵€鏈夊弬鏁伴厤缃弬鑰?https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 鎵瑰鐞嗕紭鍖?澶у箙鎻愬崌鎵归噺鎻掑叆鏇存柊鍒犻櫎鎬ц兘(瀵规暟鎹簱鏈夋€ц兘鎹熻€?浣跨敤鎵归噺鎿嶄綔搴旇€冭檻鎬ц兘闂)
          url: ${DB_URL:jdbc:mysql://localhost:3306/base_boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true}
          username: ${DB_USERNAME:root}
          password: ${DB_PASSWORD:}
        # mqtt鏁版嵁婧?
#        mqtt:
#          lazy: true
#          type: ${spring.datasource.type}
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.120.67:13306/emqx_mqtt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#          username: root
#          password: 123456
#         # tdengine鏁版嵁婧?
#        tdbd:
#          lazy: true
#          type: ${spring.datasource.type}
#          #鍘熺敓閾炬帴鏂瑰紡闇€瑕丏LL鏂囦欢鏈夌偣楹荤儲
#          #driverClassName: com.taosdata.jdbc.TSDBDriver
#          #url: url: jdbc:TAOS://192.168.120.66:6041/sensordb
#          driverClassName: com.taosdata.jdbc.rs.RestfulDriver
#          url: jdbc:TAOS-RS://192.168.120.67:6041/sensordb?timezone=Asia/Shanghai
#          username: root
#          password: bocoo123
      hikari:
        # 鏈€澶ц繛鎺ユ睜鏁伴噺
        maxPoolSize: 20
        # 鏈€灏忕┖闂茬嚎绋嬫暟閲?
        minIdle: 10
        # 閰嶇疆鑾峰彇杩炴帴绛夊緟瓒呮椂鐨勬椂闂?
        connectionTimeout: 30000
        # 鏍￠獙瓒呮椂鏃堕棿
        validationTimeout: 5000
        # 绌洪棽杩炴帴瀛樻椿鏈€澶ф椂闂达紝榛樿10鍒嗛挓
        idleTimeout: 600000
        # 姝ゅ睘鎬ф帶鍒舵睜涓繛鎺ョ殑鏈€闀跨敓鍛藉懆鏈燂紝鍊?琛ㄧず鏃犻檺鐢熷懡鍛ㄦ湡锛岄粯璁?0鍒嗛挓
        maxLifetime: 1800000
        # 澶氫箙妫€鏌ヤ竴娆¤繛鎺ョ殑娲绘€?
        keepaliveTime: 30000

--- # redis 鍗曟満閰嶇疆(鍗曟満涓庨泦缇ゅ彧鑳藉紑鍚竴涓彟涓€涓渶瑕佹敞閲婃帀)
spring.data:
  redis:
    # 鍦板潃 192.168.120.67
    host: ${REDIS_HOST:localhost}
    # 绔彛锛岄粯璁や负6379
    port: ${REDIS_PORT:6379}
    # 鏁版嵁搴撶储寮?
    database: ${REDIS_DATABASE:0}
    # 瀵嗙爜(濡傛病鏈夊瘑鐮佽娉ㄩ噴鎺?
    password: ${REDIS_PASSWORD:}
    # 杩炴帴瓒呮椂鏃堕棿
    timeout: 10s
    # 鏄惁寮€鍚痵sl
    ssl.enabled: false

redisson:
  # redis key鍓嶇紑
  keyPrefix:
  # 绾跨▼姹犳暟閲?
  threads: 4
  # Netty绾跨▼姹犳暟閲?
  nettyThreads: 8
  # 鍗曡妭鐐归厤缃?
  singleServerConfig:
    # 瀹㈡埛绔悕绉?
    clientName: ${bocoo.name}
    # 鏈€灏忕┖闂茶繛鎺ユ暟
    connectionMinimumIdleSize: 8
    # 杩炴帴姹犲ぇ灏?
    connectionPoolSize: 32
    # 杩炴帴绌洪棽瓒呮椂锛屽崟浣嶏細姣
    idleConnectionTimeout: 10000
    # 鍛戒护绛夊緟瓒呮椂锛屽崟浣嶏細姣 18073784154
    timeout: 3000
    # 鍙戝竷鍜岃闃呰繛鎺ユ睜澶у皬
    subscriptionConnectionPoolSize: 50

--- # mail 閭欢鍙戦€?
mail:
  enabled: false
  host: smtp.163.com
  port: 465
  # 鏄惁闇€瑕佺敤鎴峰悕瀵嗙爜楠岃瘉
  auth: true
  # 鍙戦€佹柟锛岄伒寰猂FC-822鏍囧噯
  from: xxx@163.com
  # 鐢ㄦ埛鍚嶏紙娉ㄦ剰锛氬鏋滀娇鐢╢oxmail閭锛屾澶剈ser涓簈q鍙凤級
  user: xxx@163.com
  # 瀵嗙爜锛堟敞鎰忥紝鏌愪簺閭闇€瑕佷负SMTP鏈嶅姟鍗曠嫭璁剧疆瀵嗙爜锛岃鎯呮煡鐪嬬浉鍏冲府鍔╋級
  pass: xxxxxxxxxx
  # 浣跨敤 STARTTLS瀹夊叏杩炴帴锛孲TARTTLS鏄绾枃鏈€氫俊鍗忚鐨勬墿灞曘€?
  starttlsEnable: true
  # 浣跨敤SSL瀹夊叏杩炴帴
  sslEnable: true
  # SMTP瓒呮椂鏃堕暱锛屽崟浣嶆绉掞紝缂虹渷鍊间笉瓒呮椂
  timeout: 0
  # Socket杩炴帴瓒呮椂鍊硷紝鍗曚綅姣锛岀己鐪佸€间笉瓒呮椂
  connectionTimeout: 0

--- # sms 鐭俊 鏀寔 闃块噷浜?鑵捐浜?浜戠墖 绛夌瓑鍚勫紡鍚勬牱鐨勭煭淇℃湇鍔″晢
# https://wind.kim/doc/start 鏂囨。鍦板潃 鍚勪釜鍘傚晢鍙悓鏃朵娇鐢?
sms:
  # 闃块噷浜?dysmsapi.aliyuncs.com
  alibaba:
    #璇锋眰鍦板潃 榛樿涓?dysmsapi.aliyuncs.com 濡傛棤鐗规畩鏀瑰彉鍙互涓嶇敤璁剧疆
    requestUrl: dysmsapi.aliyuncs.com
    #闃块噷浜戠殑accessKey
    accessKeyId: xxxxxxx
    #闃块噷浜戠殑accessKeySecret
    accessKeySecret: xxxxxxx
    #鐭俊绛惧悕
    signature: 娴嬭瘯
  tencent:
    #璇锋眰鍦板潃榛樿涓?sms.tencentcloudapi.com 濡傛棤鐗规畩鏀瑰彉鍙笉鐢ㄨ缃?
    requestUrl: sms.tencentcloudapi.com
    #鑵捐浜戠殑accessKey
    accessKeyId: xxxxxxx
    #鑵捐浜戠殑accessKeySecret
    accessKeySecret: xxxxxxx
    #鐭俊绛惧悕
    signature: 娴嬭瘯
    #鐭俊sdkAppId
    sdkAppId: appid
    #鍦板煙淇℃伅榛樿涓?ap-guangzhou 濡傛棤鐗规畩鏀瑰彉鍙笉鐢ㄨ缃?
    territory: ap-guangzhou
# SpringDoc 閰嶇疆
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true  # 鏄剧ず璇锋眰鑰楁椂
    filter: true                    # 鍚敤鎼滅储杩囨护
    try-it-out-enabled: true        # 鍚敤Try it out鍔熻兘
    default-model-expand-depth: 1   # 榛樿灞曞紑妯″瀷灞傜骇

  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true

  # 鍒嗙粍閰嶇疆
  group-configs:
    - group: '绯荤粺妯″潡'
      display-name: '绯荤粺绠＄悊鎺ュ彛'
      paths-to-match: '/**'
      packages-to-scan: 'com.bocoo.system.controller'

    - group: '浠ｇ爜鐢熸垚'
      display-name: 'generator鎺ュ彛'
      paths-to-match: '/**'
      packages-to-scan: 'com.bocoo.generator.controller'



# Knife4j 澧炲己閰嶇疆锛堜紭鍖栫増锛?
knife4j:
  enable: true
  production: false  # 鐢熶骇鐜寤鸿鏀逛负true
  basic:
    enable: true
    username: bocoo
    password: ${KNIFE4J_PASSWORD:change-me-in-env}  # 寤鸿浣跨敤鏇村己瀵嗙爜
  setting:
    language: zh-CN                # 鍥哄畾涓枃閰嶇疆
    enable-footer: true            # 鍚敤椤佃剼
    footer-custom-content: "cmx 漏 2025"  # 鑷畾涔夐〉鑴?
    enable-group: true             # 鍚敤鍒嗙粍鏍囩
    enable-request-cache: true     # 鍚敤璇锋眰缂撳瓨
    enable-document-manage: true   # 鍚敤鏂囨。绠＄悊
    swagger-model-name: "鏁版嵁妯″瀷"         # 娓呯┖妯″瀷鏍囬锛堥殣钘忔暟鎹ā鍨嬶級
# Actuator 鐩戞帶绔偣鐨勯厤缃」
management:
  endpoints:
    web:
      exposure:
        include: health  # 浠呭紑鏀惧繀瑕佺鐐?

