package com.bocoo.product.service;

import cn.hutool.extra.spring.SpringUtil;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;
import com.bocoo.common.core.service.I18nService;
import com.bocoo.product.domain.bo.ProductCategoryBo;
import com.bocoo.product.domain.bo.ProductFormulaBo;
import com.bocoo.product.domain.bo.ProductFormulaMaterialBo;
import com.bocoo.product.domain.bo.ProductFormulaOptionBo;
import com.bocoo.product.domain.bo.ProductFormulaOptionMaterialBo;
import com.bocoo.product.domain.bo.ProductFormulaOptionValueBo;
import com.bocoo.product.domain.bo.ProductFormulaRestrictionBo;
import com.bocoo.product.domain.bo.ProductFormulaUsageRuleBo;
import com.bocoo.product.domain.bo.ProductMaterialBo;
import com.bocoo.product.domain.bo.ProductMaterialTypeBo;
import com.bocoo.product.domain.bo.ProductMaterialTypeGroupBo;
import com.bocoo.product.domain.bo.ProductManufacturerBo;
import com.bocoo.product.domain.bo.ProductMediaAssetBo;
import com.bocoo.product.domain.bo.ProductMediaBindingBo;
import com.bocoo.product.domain.bo.ProductShippingTemplateBo;
import com.bocoo.product.domain.bo.ProductShippingTemplateRuleBo;
import com.bocoo.product.domain.entity.ProductCategory;
import com.bocoo.product.domain.entity.ProductChangeLog;
import com.bocoo.product.domain.entity.ProductDictItem;
import com.bocoo.product.domain.entity.ProductDictType;
import com.bocoo.product.domain.entity.ProductFormula;
import com.bocoo.product.domain.entity.ProductFormulaMaterial;
import com.bocoo.product.domain.entity.ProductFormulaOption;
import com.bocoo.product.domain.entity.ProductFormulaOptionMaterial;
import com.bocoo.product.domain.entity.ProductFormulaOptionValue;
import com.bocoo.product.domain.entity.ProductFormulaRestriction;
import com.bocoo.product.domain.entity.ProductFormulaUsageRule;
import com.bocoo.product.domain.entity.ProductFormulaVersion;
import com.bocoo.product.domain.entity.ProductMaterial;
import com.bocoo.product.domain.entity.ProductMaterialType;
import com.bocoo.product.domain.entity.ProductMaterialTypeGroup;
import com.bocoo.product.domain.entity.ProductManufacturer;
import com.bocoo.product.domain.entity.ProductMediaAsset;
import com.bocoo.product.domain.entity.ProductMediaBinding;
import com.bocoo.product.domain.entity.ProductPriceFabric;
import com.bocoo.product.domain.entity.ProductPriceFabricRule;
import com.bocoo.product.domain.entity.ProductPriceFeeRule;
import com.bocoo.product.domain.entity.ProductPriceSetting;
import com.bocoo.product.domain.entity.ProductSaleProduct;
import com.bocoo.product.domain.entity.ProductShippingTemplate;
import com.bocoo.product.domain.entity.ProductShippingTemplateRule;
import io.github.linpeilie.Converter;
import org.apache.ibatis.builder.MapperBuilderAssistant;
import org.springframework.context.support.GenericApplicationContext;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.mock;

final class ProductServiceTestSupport {

    private static boolean contextPrepared;

    private ProductServiceTestSupport() {
    }

    static synchronized void prepareMapperAndConverter() {
        prepareTableInfo(ProductCategory.class);
        prepareTableInfo(ProductChangeLog.class);
        prepareTableInfo(ProductDictItem.class);
        prepareTableInfo(ProductDictType.class);
        prepareTableInfo(ProductFormula.class);
        prepareTableInfo(ProductFormulaMaterial.class);
        prepareTableInfo(ProductFormulaOption.class);
        prepareTableInfo(ProductFormulaOptionValue.class);
        prepareTableInfo(ProductFormulaOptionMaterial.class);
        prepareTableInfo(ProductFormulaRestriction.class);
        prepareTableInfo(ProductFormulaUsageRule.class);
        prepareTableInfo(ProductFormulaVersion.class);
        prepareTableInfo(ProductMaterial.class);
        prepareTableInfo(ProductMaterialType.class);
        prepareTableInfo(ProductMaterialTypeGroup.class);
        prepareTableInfo(ProductManufacturer.class);
        prepareTableInfo(ProductMediaAsset.class);
        prepareTableInfo(ProductMediaBinding.class);
        prepareTableInfo(ProductPriceFabric.class);
        prepareTableInfo(ProductPriceFabricRule.class);
        prepareTableInfo(ProductPriceFeeRule.class);
        prepareTableInfo(ProductPriceSetting.class);
        prepareTableInfo(ProductSaleProduct.class);
        prepareTableInfo(ProductShippingTemplate.class);
        prepareTableInfo(ProductShippingTemplateRule.class);
        if (contextPrepared) {
            return;
        }
        Converter converter = mock(Converter.class);
        lenient().when(converter.convert(any(ProductCategoryBo.class), eq(ProductCategory.class))).thenAnswer(invocation -> {
            ProductCategoryBo source = invocation.getArgument(0);
            ProductCategory target = new ProductCategory();
            target.setCategoryId(source.getCategoryId());
            target.setCategoryCode(source.getCategoryCode());
            target.setCategoryNameCn(source.getCategoryNameCn());
            target.setStatus(source.getStatus());
            return target;
        });
        lenient().when(converter.convert(any(ProductMaterialBo.class), eq(ProductMaterial.class))).thenAnswer(invocation -> {
            ProductMaterialBo source = invocation.getArgument(0);
            ProductMaterial target = new ProductMaterial();
            target.setMaterialId(source.getMaterialId());
            target.setMaterialCode(source.getMaterialCode());
            target.setMaterialNameCn(source.getMaterialNameCn());
            target.setMaterialNameEn(source.getMaterialNameEn());
            target.setMaterialTypeId(source.getMaterialTypeId());
            target.setMaterialTypeCode(source.getMaterialTypeCode());
            target.setMaterialTypeNameCn(source.getMaterialTypeNameCn());
            target.setAttributeGroupId(source.getAttributeGroupId());
            target.setAttributeGroupCode(source.getAttributeGroupCode());
            target.setAttributeGroupNameCn(source.getAttributeGroupNameCn());
            target.setMaterialType(source.getMaterialType());
            target.setUnitCode(source.getUnitCode());
            target.setSecondaryUnitCode(source.getSecondaryUnitCode());
            target.setManufacturerId(source.getManufacturerId());
            target.setManufacturerCode(source.getManufacturerCode());
            target.setManufacturerName(source.getManufacturerName());
            target.setManufacturerItemNo(source.getManufacturerItemNo());
            target.setModel(source.getModel());
            target.setSpec(source.getSpec());
            target.setSpecModelText(source.getSpecModelText());
            target.setColorName(source.getColorName());
            target.setWeightValue(source.getWeightValue());
            target.setUnitPrice(source.getUnitPrice());
            target.setAuditBy(source.getAuditBy());
            target.setAuditTime(source.getAuditTime());
            target.setSortOrder(source.getSortOrder());
            target.setStatus(source.getStatus());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductFormulaBo.class), eq(ProductFormula.class))).thenAnswer(invocation -> {
            ProductFormulaBo source = invocation.getArgument(0);
            ProductFormula target = new ProductFormula();
            target.setFormulaId(source.getFormulaId());
            target.setFormulaCode(source.getFormulaCode());
            target.setFormulaName(source.getFormulaName());
            target.setCategoryId(source.getCategoryId());
            target.setCategoryCode(source.getCategoryCode());
            target.setCategoryNameCn(source.getCategoryNameCn());
            target.setProductTypeCode(source.getProductTypeCode());
            target.setProductTypeNameCn(source.getProductTypeNameCn());
            target.setMinWidthInch(source.getMinWidthInch());
            target.setMinHeightInch(source.getMinHeightInch());
            target.setMaxWidthInch(source.getMaxWidthInch());
            target.setMaxHeightInch(source.getMaxHeightInch());
            target.setSizeSummary(source.getSizeSummary());
            target.setMaterialLineCount(source.getMaterialLineCount());
            target.setConfiguredFlag(source.getConfiguredFlag());
            target.setCurrentVersionId(source.getCurrentVersionId());
            target.setCurrentVersionNo(source.getCurrentVersionNo());
            target.setCurrentVersionLabel(source.getCurrentVersionLabel());
            target.setDraftVersionNo(source.getDraftVersionNo());
            target.setLatestValidationStatus(source.getLatestValidationStatus());
            target.setLatestValidationMessage(source.getLatestValidationMessage());
            target.setLatestValidationTime(source.getLatestValidationTime());
            target.setStatus(source.getStatus());
            target.setAuditBy(source.getAuditBy());
            target.setAuditTime(source.getAuditTime());
            target.setRejectReason(source.getRejectReason());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductFormulaMaterialBo.class), eq(ProductFormulaMaterial.class))).thenAnswer(invocation -> {
            ProductFormulaMaterialBo source = invocation.getArgument(0);
            ProductFormulaMaterial target = new ProductFormulaMaterial();
            target.setFormulaMaterialId(source.getFormulaMaterialId());
            target.setFormulaId(source.getFormulaId());
            target.setLineNo(source.getLineNo());
            target.setMaterialId(source.getMaterialId());
            target.setMaterialCode(source.getMaterialCode());
            target.setMaterialNameCn(source.getMaterialNameCn());
            target.setSpecModelText(source.getSpecModelText());
            target.setAttributeGroupId(source.getAttributeGroupId());
            target.setAttributeGroupCode(source.getAttributeGroupCode());
            target.setAttributeGroupNameCn(source.getAttributeGroupNameCn());
            target.setMaterialTypeId(source.getMaterialTypeId());
            target.setMaterialTypeCode(source.getMaterialTypeCode());
            target.setMaterialTypeNameCn(source.getMaterialTypeNameCn());
            target.setUnitCode(source.getUnitCode());
            target.setDefaultFlag(source.getDefaultFlag());
            target.setRequiredFlag(source.getRequiredFlag());
            target.setUsageMode(source.getUsageMode());
            target.setUsageFormula(source.getUsageFormula());
            target.setFixedUsageQty(source.getFixedUsageQty());
            target.setCalculationUnitCode(source.getCalculationUnitCode());
            target.setRoundingMode(source.getRoundingMode());
            target.setMinUsageQty(source.getMinUsageQty());
            target.setMaxUsageQty(source.getMaxUsageQty());
            target.setLossRate(source.getLossRate());
            target.setProductionRemark(source.getProductionRemark());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductFormulaOptionBo.class), eq(ProductFormulaOption.class))).thenAnswer(invocation -> {
            ProductFormulaOptionBo source = invocation.getArgument(0);
            ProductFormulaOption target = new ProductFormulaOption();
            target.setOptionId(source.getOptionId());
            target.setFormulaId(source.getFormulaId());
            target.setOptionCode(source.getOptionCode());
            target.setOptionNameCn(source.getOptionNameCn());
            target.setOptionNameEn(source.getOptionNameEn());
            target.setSourceType(source.getSourceType());
            target.setSourceScope(source.getSourceScope());
            target.setSelectionMode(source.getSelectionMode());
            target.setDisplayMode(source.getDisplayMode());
            target.setDefaultValueCode(source.getDefaultValueCode());
            target.setDefaultValueNameCn(source.getDefaultValueNameCn());
            target.setVisibilityMode(source.getVisibilityMode());
            target.setVisibleConditionOptionCode(source.getVisibleConditionOptionCode());
            target.setVisibleConditionOptionNameCn(source.getVisibleConditionOptionNameCn());
            target.setVisibleConditionValueCode(source.getVisibleConditionValueCode());
            target.setVisibleConditionValueNameCn(source.getVisibleConditionValueNameCn());
            target.setRequiredFlag(source.getRequiredFlag());
            target.setBusinessVisibleFlag(source.getBusinessVisibleFlag());
            target.setHelpEnabled(source.getHelpEnabled());
            target.setHelpType(source.getHelpType());
            target.setHelpTitle(source.getHelpTitle());
            target.setHelpUrl(source.getHelpUrl());
            target.setHelpContent(source.getHelpContent());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductFormulaOptionValueBo.class), eq(ProductFormulaOptionValue.class))).thenAnswer(invocation -> {
            ProductFormulaOptionValueBo source = invocation.getArgument(0);
            ProductFormulaOptionValue target = new ProductFormulaOptionValue();
            target.setOptionValueId(source.getOptionValueId());
            target.setFormulaId(source.getFormulaId());
            target.setOptionId(source.getOptionId());
            target.setOptionCode(source.getOptionCode());
            target.setValueCode(source.getValueCode());
            target.setValueNameCn(source.getValueNameCn());
            target.setDefaultFlag(source.getDefaultFlag());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductFormulaOptionMaterialBo.class), eq(ProductFormulaOptionMaterial.class))).thenAnswer(invocation -> {
            ProductFormulaOptionMaterialBo source = invocation.getArgument(0);
            ProductFormulaOptionMaterial target = new ProductFormulaOptionMaterial();
            target.setOptionMaterialId(source.getOptionMaterialId());
            target.setFormulaId(source.getFormulaId());
            target.setOptionId(source.getOptionId());
            target.setOptionValueId(source.getOptionValueId());
            target.setOptionCode(source.getOptionCode());
            target.setValueCode(source.getValueCode());
            target.setFormulaMaterialId(source.getFormulaMaterialId());
            target.setMaterialId(source.getMaterialId());
            target.setMaterialCode(source.getMaterialCode());
            target.setMaterialNameCn(source.getMaterialNameCn());
            target.setRequiredFlag(source.getRequiredFlag());
            target.setDefaultFlag(source.getDefaultFlag());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductFormulaRestrictionBo.class), eq(ProductFormulaRestriction.class))).thenAnswer(invocation -> {
            ProductFormulaRestrictionBo source = invocation.getArgument(0);
            ProductFormulaRestriction target = new ProductFormulaRestriction();
            target.setRestrictionId(source.getRestrictionId());
            target.setFormulaId(source.getFormulaId());
            target.setRestrictionName(source.getRestrictionName());
            target.setTargetOptionCode(source.getTargetOptionCode());
            target.setConditionType(source.getConditionType());
            target.setConditionOptionCode(source.getConditionOptionCode());
            target.setConditionOperator(source.getConditionOperator());
            target.setConditionValueCode(source.getConditionValueCode());
            target.setConditionValueNumber(source.getConditionValueNumber());
            target.setActionType(source.getActionType());
            target.setTargetValueCode(source.getTargetValueCode());
            target.setMessageText(source.getMessageText());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductFormulaUsageRuleBo.class), eq(ProductFormulaUsageRule.class))).thenAnswer(invocation -> {
            ProductFormulaUsageRuleBo source = invocation.getArgument(0);
            ProductFormulaUsageRule target = new ProductFormulaUsageRule();
            target.setUsageRuleId(source.getUsageRuleId());
            target.setFormulaId(source.getFormulaId());
            target.setFormulaMaterialId(source.getFormulaMaterialId());
            target.setMaterialId(source.getMaterialId());
            target.setMaterialCode(source.getMaterialCode());
            target.setMaterialNameCn(source.getMaterialNameCn());
            target.setRuleName(source.getRuleName());
            target.setConditionType(source.getConditionType());
            target.setConditionOptionCode(source.getConditionOptionCode());
            target.setConditionOptionNameCn(source.getConditionOptionNameCn());
            target.setConditionValueCode(source.getConditionValueCode());
            target.setConditionValueNameCn(source.getConditionValueNameCn());
            target.setConditionExpression(source.getConditionExpression());
            target.setConditionText(source.getConditionText());
            target.setConditionKey(source.getConditionKey());
            target.setUsageMode(source.getUsageMode());
            target.setFixedUsageQty(source.getFixedUsageQty());
            target.setUsageFormula(source.getUsageFormula());
            target.setUsageFormulaText(source.getUsageFormulaText());
            target.setCalculationUnitCode(source.getCalculationUnitCode());
            target.setRoundingMode(source.getRoundingMode());
            target.setMinUsageQty(source.getMinUsageQty());
            target.setMaxUsageQty(source.getMaxUsageQty());
            target.setLossRate(source.getLossRate());
            target.setDefaultRuleFlag(source.getDefaultRuleFlag());
            target.setProductionRemark(source.getProductionRemark());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductManufacturerBo.class), eq(ProductManufacturer.class))).thenAnswer(invocation -> {
            ProductManufacturerBo source = invocation.getArgument(0);
            ProductManufacturer target = new ProductManufacturer();
            target.setManufacturerId(source.getManufacturerId());
            target.setManufacturerCode(source.getManufacturerCode());
            target.setManufacturerName(source.getManufacturerName());
            target.setManufacturerShortName(source.getManufacturerShortName());
            target.setManufacturerFlag(source.getManufacturerFlag());
            target.setSupplierFlag(source.getSupplierFlag());
            target.setContactName(source.getContactName());
            target.setContactPhone(source.getContactPhone());
            target.setAddress(source.getAddress());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductMaterialTypeGroupBo.class), eq(ProductMaterialTypeGroup.class))).thenAnswer(invocation -> {
            ProductMaterialTypeGroupBo source = invocation.getArgument(0);
            ProductMaterialTypeGroup target = new ProductMaterialTypeGroup();
            target.setGroupId(source.getGroupId());
            target.setGroupCode(source.getGroupCode());
            target.setGroupNameCn(source.getGroupNameCn());
            target.setGroupNameEn(source.getGroupNameEn());
            target.setSystemFlag(source.getSystemFlag());
            target.setEditableFlag(source.getEditableFlag());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductMaterialTypeBo.class), eq(ProductMaterialType.class))).thenAnswer(invocation -> {
            ProductMaterialTypeBo source = invocation.getArgument(0);
            ProductMaterialType target = new ProductMaterialType();
            target.setMaterialTypeId(source.getMaterialTypeId());
            target.setMaterialTypeCode(source.getMaterialTypeCode());
            target.setMaterialTypeNameCn(source.getMaterialTypeNameCn());
            target.setMaterialTypeNameEn(source.getMaterialTypeNameEn());
            target.setAttributeGroupId(source.getAttributeGroupId());
            target.setAttributeGroupCode(source.getAttributeGroupCode());
            target.setAttributeGroupNameCn(source.getAttributeGroupNameCn());
            target.setSystemFlag(source.getSystemFlag());
            target.setEditableFlag(source.getEditableFlag());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductMediaAssetBo.class), eq(ProductMediaAsset.class))).thenAnswer(invocation -> {
            ProductMediaAssetBo source = invocation.getArgument(0);
            ProductMediaAsset target = new ProductMediaAsset();
            target.setAssetId(source.getAssetId());
            target.setAssetCode(source.getAssetCode());
            target.setAssetNameCn(source.getAssetNameCn());
            target.setAssetNameEn(source.getAssetNameEn());
            target.setAssetType(source.getAssetType());
            target.setUsageType(source.getUsageType());
            target.setLanguageCode(source.getLanguageCode());
            target.setVisibility(source.getVisibility());
            target.setOssId(source.getOssId());
            target.setUrl(source.getUrl());
            target.setAltText(source.getAltText());
            target.setVersionNo(source.getVersionNo());
            target.setStatus(source.getStatus());
            target.setDelFlag(source.getDelFlag());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductMediaBindingBo.class), eq(ProductMediaBinding.class))).thenAnswer(invocation -> {
            ProductMediaBindingBo source = invocation.getArgument(0);
            ProductMediaBinding target = new ProductMediaBinding();
            target.setBindingId(source.getBindingId());
            target.setAssetId(source.getAssetId());
            target.setAssetCode(source.getAssetCode());
            target.setTargetType(source.getTargetType());
            target.setTargetId(source.getTargetId());
            target.setTargetCode(source.getTargetCode());
            target.setUsageType(source.getUsageType());
            target.setVisibility(source.getVisibility());
            target.setLanguageCode(source.getLanguageCode());
            target.setRequiredForPublish(source.getRequiredForPublish());
            target.setSortOrder(source.getSortOrder());
            target.setStatus(source.getStatus());
            target.setDelFlag(source.getDelFlag());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductShippingTemplateBo.class), eq(ProductShippingTemplate.class))).thenAnswer(invocation -> {
            ProductShippingTemplateBo source = invocation.getArgument(0);
            ProductShippingTemplate target = new ProductShippingTemplate();
            target.setShippingTemplateId(source.getShippingTemplateId());
            target.setTenantId(source.getTenantId());
            target.setTemplateCode(source.getTemplateCode());
            target.setTemplateName(source.getTemplateName());
            target.setCurrencyCode(source.getCurrencyCode());
            target.setDefaultFlag(source.getDefaultFlag());
            target.setStatus(source.getStatus());
            target.setSortOrder(source.getSortOrder());
            target.setDelFlag(source.getDelFlag());
            target.setRemark(source.getRemark());
            return target;
        });
        lenient().when(converter.convert(any(ProductShippingTemplateRuleBo.class), eq(ProductShippingTemplateRule.class))).thenAnswer(invocation -> {
            ProductShippingTemplateRuleBo source = invocation.getArgument(0);
            ProductShippingTemplateRule target = new ProductShippingTemplateRule();
            target.setShippingTemplateRuleId(source.getShippingTemplateRuleId());
            target.setTenantId(source.getTenantId());
            target.setShippingTemplateId(source.getShippingTemplateId());
            target.setFeeCode(source.getFeeCode());
            target.setFeeName(source.getFeeName());
            target.setMinAreaSqft(source.getMinAreaSqft());
            target.setMaxAreaSqft(source.getMaxAreaSqft());
            target.setFormulaText(source.getFormulaText());
            target.setSortOrder(source.getSortOrder());
            target.setDelFlag(source.getDelFlag());
            target.setRemark(source.getRemark());
            return target;
        });
        GenericApplicationContext context = new GenericApplicationContext();
        context.registerBean(Converter.class, () -> converter);
        context.registerBean(I18nService.class, () -> mock(I18nService.class));
        context.refresh();
        new SpringUtil().setApplicationContext(context);
        contextPrepared = true;
    }

    private static void prepareTableInfo(Class<?> entityClass) {
        try {
            TableInfoHelper.initTableInfo(new MapperBuilderAssistant(new MybatisConfiguration(), ""), entityClass);
        } catch (IllegalStateException ignored) {
            // Already initialized for this JVM.
        }
    }
}
