allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - vxe-table@4.19.15
overrides:
  braces: 3.0.3
  css-what: 5.0.1
  micromatch: 4.0.8
  nth-check: 2.0.1
  postcss: 8.5.15
  '@page-agent/core': 'file:vendor/page-agent/page-agent-core-1.10.0-amu.6.tgz'
  '@page-agent/llms': 'file:vendor/page-agent/page-agent-llms-1.10.0-amu.6.tgz'
  '@page-agent/page-controller': 'file:vendor/page-agent/page-agent-page-controller-1.10.0-amu.6.tgz'
  '@page-agent/ui': 'file:vendor/page-agent/page-agent-ui-1.10.0-amu.6.tgz'
  page-agent: 'file:vendor/page-agent/page-agent-1.10.0-amu.6.tgz'
