<template>
  <div class="order-detail" v-loading="loading">
    <header class="detail-bar"><div><el-button link icon="ArrowLeft" @click="router.back()" /><h1>{{ t('dealer.sales.detail') }}</h1><el-tag>{{ documentStatusText(t, document.documentStatus) }}</el-tag></div><div class="actions">
      <el-button v-if="document.documentStatus==='SUBMITTED'" v-hasPermi="['dealer:sales:cancel']" type="danger" plain @click="cancelOrder">{{ t('dealer.sales.cancel') }}</el-button>
      <el-button v-if="document.documentStatus==='SUBMITTED'&&document.paymentStatus==='UNPAID'" v-hasPermi="['dealer:sales:payment']" @click="paymentVisible=true">{{ t('dealer.sales.payment') }}</el-button>
      <el-button v-if="document.paymentStatus==='PAID'&&document.productionStatus==='PENDING'" v-hasPermi="['dealer:sales:production']" @click="action('startProduction')">{{ t('dealer.sales.startProduction') }}</el-button>
      <el-button v-if="document.productionStatus==='IN_PRODUCTION'" v-hasPermi="['dealer:sales:production']" @click="action('completeProduction')">{{ t('dealer.sales.completeProduction') }}</el-button>
      <el-button v-if="document.productionStatus==='COMPLETED'&&document.shipmentStatus==='UNSHIPPED'" v-hasPermi="['dealer:sales:shipment']" @click="shipVisible=true">{{ t('dealer.sales.ship') }}</el-button>
      <el-button v-if="document.shipmentStatus==='SHIPPED'" v-hasPermi="['dealer:sales:deliver']" type="primary" @click="action('deliver')">{{ t('dealer.sales.deliver') }}</el-button>
      <el-dropdown v-hasPermi="['dealer:sales:document']" @command="openPdf"><el-button icon="Printer">PDF<el-icon><ArrowDown /></el-icon></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="ORDER">{{ t('dealer.sales.orderPdf') }}</el-dropdown-item><el-dropdown-item v-hasPermi="['dealer:sales:production']" command="PRODUCTION">{{ t('dealer.sales.productionPdf') }}</el-dropdown-item></el-dropdown-menu></template></el-dropdown>
      <el-button v-hasPermi="['dealer:sales:document']" icon="Download" @click="exportExcel">{{ t('common.export') }}</el-button>
      <el-button v-hasPermi="['dealer:sales:email']" icon="Message" @click="emailVisible=true">{{ t('dealer.sales.email') }}</el-button>
    </div></header>
    <section class="facts"><div><label>{{ t('dealer.sales.quoteNo') }}</label><b>{{ document.quoteNo }}</b></div><div><label>{{ t('dealer.sales.orderNo') }}</label><b>{{ document.orderNo||'-' }}</b></div><div><label>{{ t('dealer.sales.customer') }}</label><b>{{ document.customerName }}</b></div><div><label>{{ t('dealer.sales.merchant') }}</label><b>{{ document.merchantName }}</b></div><div><label>{{ t('dealer.sales.project') }}</label><b>{{ document.projectName||'-' }}</b></div><div><label>{{ t('dealer.sales.address') }}</label><b>{{ document.shippingAddress||'-' }}</b></div></section>
    <section class="progress"><el-steps :active="progress" finish-status="success"><el-step :title="t('dealer.sales.progress.unpaid')"/><el-step :title="t('dealer.sales.progress.productionPending')"/><el-step :title="t('dealer.sales.progress.producing')"/><el-step :title="t('dealer.sales.progress.shippingPending')"/><el-step :title="t('dealer.sales.progress.shipped')"/><el-step :title="t('dealer.sales.progress.completed')"/></el-steps></section>
    <section class="items"><h3>{{ t('dealer.sales.items') }}</h3><el-table :data="document.items" border><el-table-column prop="lineNo" label="#" width="55"/><el-table-column prop="roomLocation" :label="t('dealer.sales.room')"/><el-table-column prop="saleProductName" :label="t('dealer.sales.product')" min-width="180"/><el-table-column prop="orderWidthInch" :label="t('dealer.sales.width')" width="110"/><el-table-column prop="orderHeightInch" :label="t('dealer.sales.height')" width="110"/><el-table-column prop="quantity" :label="t('dealer.sales.quantity')" width="80"/><el-table-column prop="configurationSummary" :label="t('dealer.sales.configuration')" min-width="230"/><el-table-column :label="t('dealer.sales.totalAmount')" width="120" align="right"><template #default="{row}">{{ money(row.lineAmount) }}</template></el-table-column></el-table></section>
    <section class="lower"><div class="timeline"><h3>{{ t('dealer.sales.events') }}</h3><el-timeline><el-timeline-item v-for="e in document.events||[]" :key="e.salesEventId" :timestamp="formatUtc(e.occurredTime,'YYYY-MM-DD HH:mm')"><b>{{ e.eventType }}</b> {{ e.operatorName }}<p>{{ e.eventNote }}</p></el-timeline-item></el-timeline></div><div class="summary"><p>{{ t('dealer.sales.listAmount') }} <b>{{ money(document.listAmount) }}</b></p><p>{{ t('dealer.sales.discountAmount') }} <b>{{ money(document.discountAmount) }}</b></p><p>{{ t('dealer.sales.shippingAmount') }} <b>{{ money(document.shippingAmount) }}</b></p><p class="grand">{{ t('dealer.sales.totalAmount') }} <b>{{ money(document.totalAmount) }}</b></p></div></section>
    <el-dialog v-model="paymentVisible" :title="t('dealer.sales.payment')" width="520"><el-form label-width="110"><el-form-item :label="t('dealer.sales.paymentMethod')"><el-select v-model="payment.paymentMethod"><el-option label="Bank Transfer" value="BANK_TRANSFER"/><el-option label="Cash" value="CASH"/></el-select></el-form-item><el-form-item :label="t('dealer.sales.paymentAmount')"><el-input-number v-model="payment.paidAmount" :precision="2" :controls="false"/></el-form-item><el-form-item :label="t('dealer.sales.paymentReference')"><el-input v-model="payment.paymentReference"/></el-form-item><el-form-item :label="t('dealer.sales.paymentProof')"><FileUpload v-model="payment.paymentProofMediaId" :limit="1" :file-type="['pdf','png','jpg','jpeg']" /></el-form-item></el-form><template #footer><el-button @click="paymentVisible=false">{{t('common.cancel')}}</el-button><el-button type="primary" @click="confirmPayment">{{t('common.confirm')}}</el-button></template></el-dialog>
    <el-dialog v-model="shipVisible" :title="t('dealer.sales.ship')" width="480"><el-form label-width="100"><el-form-item :label="t('dealer.sales.carrier')"><el-input v-model="shipment.carrierName"/></el-form-item><el-form-item :label="t('dealer.sales.trackingNo')"><el-input v-model="shipment.trackingNo"/></el-form-item></el-form><template #footer><el-button @click="shipVisible=false">{{t('common.cancel')}}</el-button><el-button type="primary" @click="confirmShip">{{t('common.confirm')}}</el-button></template></el-dialog>
    <el-dialog v-model="emailVisible" :title="t('dealer.sales.email')" width="500"><el-form label-width="90"><el-form-item :label="t('dealer.sales.recipientEmail')"><el-input v-model="email.recipient"/></el-form-item><el-form-item :label="t('dealer.sales.message')"><el-input v-model="email.message" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="emailVisible=false">{{t('common.cancel')}}</el-button><el-button type="primary" @click="sendEmail">{{t('common.confirm')}}</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';import { useI18n } from 'vue-i18n';import { useRoute,useRouter } from 'vue-router';import { ElMessage, ElMessageBox } from 'element-plus';import { ArrowDown } from '@element-plus/icons-vue';import { salesApi,type SalesDocument } from '@/api/dealer-sales';import { formatUtc } from '@/utils/datetime';import { download } from '@/utils/request';import FileUpload from '@/components/FileUpload/index.vue'
import { documentStatusText } from './salesPresentation'
const {t}=useI18n();const route=useRoute();const router=useRouter();const id=String(route.params.id);const document=reactive<SalesDocument>({items:[]});const loading=ref(false);const paymentVisible=ref(false);const shipVisible=ref(false);const emailVisible=ref(false);const payment=reactive({paymentMethod:'BANK_TRANSFER',paidAmount:0,paymentReference:'',paymentProofMediaId:''});const shipment=reactive({carrierName:'',trackingNo:''});const email=reactive({recipient:'',documentType:'ORDER',message:''})
const progress=computed(()=>document.shipmentStatus==='DELIVERED'?6:document.shipmentStatus==='SHIPPED'?5:document.productionStatus==='COMPLETED'?4:document.productionStatus==='IN_PRODUCTION'?3:document.paymentStatus==='PAID'?2:1)
async function load(){loading.value=true;try{Object.assign(document,(await salesApi.get(id)).data);payment.paidAmount=document.totalAmount||0;email.recipient=document.customerEmail||''}finally{loading.value=false}}
function money(v?:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:document.currencyCode||'USD'}).format(v||0)}
async function action(name:'startProduction'|'completeProduction'|'deliver'){await salesApi[name](id);ElMessage.success(t('common.operationSuccess'));await load()}
async function cancelOrder(){const result=await ElMessageBox.prompt(t('dealer.sales.cancelReason'),t('dealer.sales.cancel'),{inputType:'textarea'});await salesApi.cancel(id,result.value);ElMessage.success(t('common.operationSuccess'));await load()}
async function confirmPayment(){await salesApi.payment(id,{...payment,paymentProofMediaId:payment.paymentProofMediaId?Number(payment.paymentProofMediaId):undefined});paymentVisible.value=false;await load()}async function confirmShip(){await salesApi.ship(id,shipment);shipVisible.value=false;await load()}async function sendEmail(){await salesApi.email(id,email);emailVisible.value=false;ElMessage.success(t('common.operationSuccess'))}
async function openPdf(type:string){const blob=await salesApi.pdf(id,type);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}
function exportExcel(){download(`dealer/sales-documents/${id}/export`,{},`${document.orderNo||document.quoteNo||id}.xlsx`)}
onMounted(load)
</script>
<style scoped>
.order-detail{padding:16px;background:#f4f6f9;min-height:calc(100vh - 88px)}.detail-bar,.detail-bar>div,.actions,.facts,.lower{display:flex;align-items:center;gap:10px}.detail-bar{justify-content:space-between}.detail-bar h1{font-size:20px}.facts,.progress,.items,.lower{margin-top:12px;padding:16px;border:1px solid #dfe5ed;background:#fff}.facts{display:grid;grid-template-columns:repeat(3,1fr)}.facts div{display:flex;flex-direction:column;gap:4px}.facts label{color:#667085;font-size:12px}.items h3,.timeline h3{margin-top:0}.lower{align-items:flex-start}.timeline{flex:1}.summary{width:300px}.summary p{display:flex;justify-content:space-between}.grand{font-size:18px;color:#1677ff}
</style>
