const fs = require('fs');
const path = require('path');
const {
  readSourceLocale,
  rootDir
} = require('./lib.ts');

const outputFile = path.join(rootDir, 'admin-ui', 'src', 'types', 'i18n-keys.d.ts');
const keysPerLine = 16;

function quote(value) {
  return JSON.stringify(value);
}

function chunk(items, size) {
  const chunks = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

function main() {
  const { messages, duplicates } = readSourceLocale('en_US');
  if (duplicates.length) {
    console.error(`[i18n:types] failed with ${duplicates.length} duplicate key(s).`);
    process.exit(1);
  }

  const keys = Object.keys(messages).sort();
  const lines = [
    '/* eslint-disable */',
    '// Generated by pnpm i18n:types. Do not edit manually.',
    '',
    'export interface I18nMessageSchema {'
  ];

  for (const group of chunk(keys, keysPerLine)) {
    lines.push(`  ${group.map((key) => `${quote(key)}: string;`).join(' ')}`);
  }

  lines.push(
    '}',
    '',
    'export type I18nKey = keyof I18nMessageSchema & string',
    '',
    "declare module 'vue-i18n' {",
    '  export interface DefineLocaleMessage extends I18nMessageSchema {}',
    '}',
    ''
  );

  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, `${lines.join('\n')}`, 'utf8');
  console.log(`[i18n:types] generated ${keys.length} key type(s) at ${path.relative(rootDir, outputFile)}.`);
}

main();
